<?php
return array (
  'title' => '中介服务地区',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '北京',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '上海',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '广州',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '深圳',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '成都',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '武汉',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '南京',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '杭州',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '青岛',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '鞍山',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '长春',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '长沙',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '大连',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '贵阳',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3401',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '哈尔滨',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3402',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '合肥',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3403',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '济南',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3404',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '昆明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '兰州',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3406',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '南昌',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3407',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '南宁',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3408',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '宁波',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3409',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '沈阳',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3410',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '石家庄',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3411',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '太原',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3412',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3413 => 
    array (
      'linkageid' => '3413',
      'name' => '天津',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3413',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '温州',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3414',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '乌鲁木齐',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3415',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '厦门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3416',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '郑州',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3417',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => '重庆',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3418',
      'keyid' => '3386',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
  ),
);
?>