<?php
return array (
  'title' => '中介办理国家',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '美国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3419',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '英国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3420',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '澳洲',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3421',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '加拿大',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3422',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '德国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3423',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '法国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3424',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '日本',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3425',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3426 => 
    array (
      'linkageid' => '3426',
      'name' => '香港',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3426',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '新加坡',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3427',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '阿根廷',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3428',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '爱尔兰',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3429',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '北欧',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3430',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '波兰',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3431',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3432 => 
    array (
      'linkageid' => '3432',
      'name' => '俄罗斯',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3432',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '韩国',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '荷兰',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '马来西亚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '乌克兰',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3436',
      'keyid' => '3387',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
  ),
);
?>