<?php
return array (
  'title' => '26个专业',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3552 => 
    array (
      'linkageid' => '3552',
      'name' => '商科',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3552,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3553 => 
    array (
      'linkageid' => '3553',
      'name' => '经济学',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3553,3615,3616,3617,3618,3619,3620,3621,3622,3623,3624,3625,3626',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3554 => 
    array (
      'linkageid' => '3554',
      'name' => '工程',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3554,3598,3599,3600,3601,3602,3603,3604,3605,3606,3607,3608,3609,3610,3611,3612,3613,3614',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3555 => 
    array (
      'linkageid' => '3555',
      'name' => '教育',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3555,3657,3658,3659,3660,3661,3662,3663,3664,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674,3675',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3556 => 
    array (
      'linkageid' => '3556',
      'name' => '数学统计',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3556,3632,3633,3634',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3557 => 
    array (
      'linkageid' => '3557',
      'name' => '传播学',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3557,3627,3628,3629,3630,3631',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3558 => 
    array (
      'linkageid' => '3558',
      'name' => '艺术与设计',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3558,3635,3636,3637,3638,3639,3640,3641,3642,3643,3644,3645,3646,3647,3648,3649,3650,3651,3652,3653,3654,3655,3656',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3559 => 
    array (
      'linkageid' => '3559',
      'name' => '法律',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3559,3688,3689,3690,3691,3692,3693,3694,3695,3696,3697,3698,3699,3700,3701',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3560 => 
    array (
      'linkageid' => '3560',
      'name' => '公共事务',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3560,3676,3677,3678',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3561 => 
    array (
      'linkageid' => '3561',
      'name' => '语言与文学',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3561,3679,3680,3681,3682,3683,3684,3685,3686,3687',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3562 => 
    array (
      'linkageid' => '3562',
      'name' => '历史与文化',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3562,3744,3745,3746,3747,3748,3749,3750,3751,3752,3753',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3563 => 
    array (
      'linkageid' => '3563',
      'name' => '社会与哲学',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3563,3754,3755,3756,3757',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3564 => 
    array (
      'linkageid' => '3564',
      'name' => '生物',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3564,3702,3703,3704,3705,3706,3707,3708,3709,3710,3711,3712,3713',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3565 => 
    array (
      'linkageid' => '3565',
      'name' => '心理学',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3565,3727,3728,3729,3730,3731,3732,3733,3734,3735,3736,3737',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3567 => 
    array (
      'linkageid' => '3567',
      'name' => '环境',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3567,3738,3739,3740,3741,3742,3743',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3568 => 
    array (
      'linkageid' => '3568',
      'name' => '医学',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3568,3758,3759,3760,3761,3762,3763,3764,3765,3766',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3569 => 
    array (
      'linkageid' => '3569',
      'name' => '地球科学',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3569,3767,3768,3769,3770,3771,3772',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3570 => 
    array (
      'linkageid' => '3570',
      'name' => '政治与外交',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3570,3778,3779,3780',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3572 => 
    array (
      'linkageid' => '3572',
      'name' => '公共卫生',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3572,3781,3782,3783,3784',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3573 => 
    array (
      'linkageid' => '3573',
      'name' => '物理',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3573,3785,3786,3787,3788,3789,3790,3791,3792,3793',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3574 => 
    array (
      'linkageid' => '3574',
      'name' => '化学',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3574,3796,3797,3798,3799,3800',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3575 => 
    array (
      'linkageid' => '3575',
      'name' => '食品与营养',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3575,3794,3795',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3576 => 
    array (
      'linkageid' => '3576',
      'name' => '城市规划与设计',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3576,3801,3802,3803',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3577 => 
    array (
      'linkageid' => '3577',
      'name' => '农业与林业',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3577,3804,3805',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3578 => 
    array (
      'linkageid' => '3578',
      'name' => '金融',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3578',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3579 => 
    array (
      'linkageid' => '3579',
      'name' => '管理学',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3579',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3580 => 
    array (
      'linkageid' => '3580',
      'name' => '市场营销',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3580',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3581 => 
    array (
      'linkageid' => '3581',
      'name' => '工商管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3581',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3582 => 
    array (
      'linkageid' => '3582',
      'name' => '人力资源管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3582',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3583 => 
    array (
      'linkageid' => '3583',
      'name' => '会计',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3583',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3584 => 
    array (
      'linkageid' => '3584',
      'name' => '管理信息系统',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3584',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3585 => 
    array (
      'linkageid' => '3585',
      'name' => '国际商务',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3585',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3586 => 
    array (
      'linkageid' => '3586',
      'name' => '酒店/旅游管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3586',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3587 => 
    array (
      'linkageid' => '3587',
      'name' => '奢侈品管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3587',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3588 => 
    array (
      'linkageid' => '3588',
      'name' => '供应链管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3588',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3589 => 
    array (
      'linkageid' => '3589',
      'name' => '创业学',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3589',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3590 => 
    array (
      'linkageid' => '3590',
      'name' => '房地产',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3590',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3591 => 
    array (
      'linkageid' => '3591',
      'name' => '商业分析',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3591',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3592 => 
    array (
      'linkageid' => '3592',
      'name' => '会展管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3592',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3593 => 
    array (
      'linkageid' => '3593',
      'name' => '技术管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3593',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3594 => 
    array (
      'linkageid' => '3594',
      'name' => '体育管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3594',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3595 => 
    array (
      'linkageid' => '3595',
      'name' => '文化管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3595',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3596 => 
    array (
      'linkageid' => '3596',
      'name' => '电子商务',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3596',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3597 => 
    array (
      'linkageid' => '3597',
      'name' => '知识管理',
      'style' => '',
      'parentid' => '3552',
      'child' => '0',
      'arrchildid' => '3597',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3598 => 
    array (
      'linkageid' => '3598',
      'name' => '工程管理',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3598',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3599 => 
    array (
      'linkageid' => '3599',
      'name' => '电气工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3599',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3600 => 
    array (
      'linkageid' => '3600',
      'name' => '通信工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3600',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3601 => 
    array (
      'linkageid' => '3601',
      'name' => '机械工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3601',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3602 => 
    array (
      'linkageid' => '3602',
      'name' => '土木工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3602',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3603 => 
    array (
      'linkageid' => '3603',
      'name' => '材料科学与工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3603',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3604 => 
    array (
      'linkageid' => '3604',
      'name' => '生物医学工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3604',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3605 => 
    array (
      'linkageid' => '3605',
      'name' => '能源与动力工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3605',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3606 => 
    array (
      'linkageid' => '3606',
      'name' => '金融工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3606',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3607 => 
    array (
      'linkageid' => '3607',
      'name' => '纳米技术',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3607',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3608 => 
    array (
      'linkageid' => '3608',
      'name' => '航空航天工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3608',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3609 => 
    array (
      'linkageid' => '3609',
      'name' => '交通运输工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3609',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3610 => 
    array (
      'linkageid' => '3610',
      'name' => '石油工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3610',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3611 => 
    array (
      'linkageid' => '3611',
      'name' => '工业工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3611',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3612 => 
    array (
      'linkageid' => '3612',
      'name' => '环境工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3612',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3613 => 
    array (
      'linkageid' => '3613',
      'name' => '化学工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3613',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3614 => 
    array (
      'linkageid' => '3614',
      'name' => '计算机工程',
      'style' => '',
      'parentid' => '3554',
      'child' => '0',
      'arrchildid' => '3614',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3615 => 
    array (
      'linkageid' => '3615',
      'name' => '临床医学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3615',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3616 => 
    array (
      'linkageid' => '3616',
      'name' => '康复医学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3616',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3617 => 
    array (
      'linkageid' => '3617',
      'name' => '护理学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3617',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3618 => 
    array (
      'linkageid' => '3618',
      'name' => '牙医',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3618',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3619 => 
    array (
      'linkageid' => '3619',
      'name' => '生物医学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3619',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3620 => 
    array (
      'linkageid' => '3620',
      'name' => '遗传学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3620',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3621 => 
    array (
      'linkageid' => '3621',
      'name' => '生理学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3621',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3622 => 
    array (
      'linkageid' => '3622',
      'name' => '免疫学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3622',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3623 => 
    array (
      'linkageid' => '3623',
      'name' => '兽医',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3623',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3624 => 
    array (
      'linkageid' => '3624',
      'name' => '病理学',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3624',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3625 => 
    array (
      'linkageid' => '3625',
      'name' => '中医药',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3625',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3626 => 
    array (
      'linkageid' => '3626',
      'name' => '医院管理',
      'style' => '',
      'parentid' => '3553',
      'child' => '0',
      'arrchildid' => '3626',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3627 => 
    array (
      'linkageid' => '3627',
      'name' => '历史',
      'style' => '',
      'parentid' => '3557',
      'child' => '0',
      'arrchildid' => '3627',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3628 => 
    array (
      'linkageid' => '3628',
      'name' => '文化',
      'style' => '',
      'parentid' => '3557',
      'child' => '0',
      'arrchildid' => '3628',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3629 => 
    array (
      'linkageid' => '3629',
      'name' => '考古学',
      'style' => '',
      'parentid' => '3557',
      'child' => '0',
      'arrchildid' => '3629',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3630 => 
    array (
      'linkageid' => '3630',
      'name' => '人类学',
      'style' => '',
      'parentid' => '3557',
      'child' => '0',
      'arrchildid' => '3630',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3631 => 
    array (
      'linkageid' => '3631',
      'name' => '中国研究',
      'style' => '',
      'parentid' => '3557',
      'child' => '0',
      'arrchildid' => '3631',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3632 => 
    array (
      'linkageid' => '3632',
      'name' => '地区研究',
      'style' => '',
      'parentid' => '3556',
      'child' => '0',
      'arrchildid' => '3632',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3633 => 
    array (
      'linkageid' => '3633',
      'name' => '国际关系',
      'style' => '',
      'parentid' => '3556',
      'child' => '0',
      'arrchildid' => '3633',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3634 => 
    array (
      'linkageid' => '3634',
      'name' => '政治',
      'style' => '',
      'parentid' => '3556',
      'child' => '0',
      'arrchildid' => '3634',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3635 => 
    array (
      'linkageid' => '3635',
      'name' => '影视',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3635',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3636 => 
    array (
      'linkageid' => '3636',
      'name' => '音乐',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3636',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3637 => 
    array (
      'linkageid' => '3637',
      'name' => '建筑学',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3637',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3638 => 
    array (
      'linkageid' => '3638',
      'name' => '戏剧',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3638',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3639 => 
    array (
      'linkageid' => '3639',
      'name' => '编剧',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3639',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3640 => 
    array (
      'linkageid' => '3640',
      'name' => '舞蹈',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3640',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3641 => 
    array (
      'linkageid' => '3641',
      'name' => '摄影',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3641',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3642 => 
    array (
      'linkageid' => '3642',
      'name' => '平面设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3642',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3643 => 
    array (
      'linkageid' => '3643',
      'name' => '绘画',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3643',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3644 => 
    array (
      'linkageid' => '3644',
      'name' => '服装设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3644',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3645 => 
    array (
      'linkageid' => '3645',
      'name' => '室内设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3645',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3646 => 
    array (
      'linkageid' => '3646',
      'name' => '艺术管理',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3646',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3647 => 
    array (
      'linkageid' => '3647',
      'name' => '制陶',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3647',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3648 => 
    array (
      'linkageid' => '3648',
      'name' => '表演',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3648',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3649 => 
    array (
      'linkageid' => '3649',
      'name' => '音响设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3649',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3650 => 
    array (
      'linkageid' => '3650',
      'name' => '灯光设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3650',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3651 => 
    array (
      'linkageid' => '3651',
      'name' => '工业设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3651',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3652 => 
    array (
      'linkageid' => '3652',
      'name' => '雕塑',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3652',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3653 => 
    array (
      'linkageid' => '3653',
      'name' => '家具设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3653',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3654 => 
    array (
      'linkageid' => '3654',
      'name' => '版画',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3654',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3655 => 
    array (
      'linkageid' => '3655',
      'name' => '珠宝设计',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3655',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3656 => 
    array (
      'linkageid' => '3656',
      'name' => '娱乐管理',
      'style' => '',
      'parentid' => '3558',
      'child' => '0',
      'arrchildid' => '3656',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3657 => 
    array (
      'linkageid' => '3657',
      'name' => '英语教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3657',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3658 => 
    array (
      'linkageid' => '3658',
      'name' => '幼儿教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3658',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3659 => 
    array (
      'linkageid' => '3659',
      'name' => '教育研究',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3659',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3660 => 
    array (
      'linkageid' => '3660',
      'name' => '教育管理',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3660',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3661 => 
    array (
      'linkageid' => '3661',
      'name' => '教育咨询',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3661',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3662 => 
    array (
      'linkageid' => '3662',
      'name' => '特殊教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3662',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3663 => 
    array (
      'linkageid' => '3663',
      'name' => '高等教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3663',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3664 => 
    array (
      'linkageid' => '3664',
      'name' => '数学教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3664',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3665 => 
    array (
      'linkageid' => '3665',
      'name' => '教学与学习',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3665',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3666 => 
    array (
      'linkageid' => '3666',
      'name' => '体育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3666',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3667 => 
    array (
      'linkageid' => '3667',
      'name' => '成人教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3667',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3668 => 
    array (
      'linkageid' => '3668',
      'name' => '小学教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3668',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3669 => 
    array (
      'linkageid' => '3669',
      'name' => '高中教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3669',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3670 => 
    array (
      'linkageid' => '3670',
      'name' => '教育心理学',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3670',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3671 => 
    array (
      'linkageid' => '3671',
      'name' => '师范教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3671',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3672 => 
    array (
      'linkageid' => '3672',
      'name' => '汉语教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3672',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3673 => 
    array (
      'linkageid' => '3673',
      'name' => '教育技术',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3673',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3674 => 
    array (
      'linkageid' => '3674',
      'name' => '人类发展',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3674',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3675 => 
    array (
      'linkageid' => '3675',
      'name' => '音乐教育',
      'style' => '',
      'parentid' => '3555',
      'child' => '0',
      'arrchildid' => '3675',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3676 => 
    array (
      'linkageid' => '3676',
      'name' => '社会学',
      'style' => '',
      'parentid' => '3560',
      'child' => '0',
      'arrchildid' => '3676',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3677 => 
    array (
      'linkageid' => '3677',
      'name' => '宗教',
      'style' => '',
      'parentid' => '3560',
      'child' => '0',
      'arrchildid' => '3677',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3678 => 
    array (
      'linkageid' => '3678',
      'name' => '哲学',
      'style' => '',
      'parentid' => '3560',
      'child' => '0',
      'arrchildid' => '3678',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3679 => 
    array (
      'linkageid' => '3679',
      'name' => '文学',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3679',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3680 => 
    array (
      'linkageid' => '3680',
      'name' => '英语',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3680',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3681 => 
    array (
      'linkageid' => '3681',
      'name' => '语言学',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3681',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3682 => 
    array (
      'linkageid' => '3682',
      'name' => '翻译',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3682',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3683 => 
    array (
      'linkageid' => '3683',
      'name' => '法语',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3683',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3684 => 
    array (
      'linkageid' => '3684',
      'name' => '阿拉伯语',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3684',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3685 => 
    array (
      'linkageid' => '3685',
      'name' => '希腊语',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3685',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3686 => 
    array (
      'linkageid' => '3686',
      'name' => '拉丁语',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3686',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3687 => 
    array (
      'linkageid' => '3687',
      'name' => '荷兰语',
      'style' => '',
      'parentid' => '3561',
      'child' => '0',
      'arrchildid' => '3687',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3688 => 
    array (
      'linkageid' => '3688',
      'name' => '法医/法证',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3688',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3689 => 
    array (
      'linkageid' => '3689',
      'name' => '商法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3689',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3690 => 
    array (
      'linkageid' => '3690',
      'name' => '国际法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3690',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3691 => 
    array (
      'linkageid' => '3691',
      'name' => '国际商法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3691',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3692 => 
    array (
      'linkageid' => '3692',
      'name' => 'LLM法律硕士',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3692',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3693 => 
    array (
      'linkageid' => '3693',
      'name' => '金融法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3693',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3694 => 
    array (
      'linkageid' => '3694',
      'name' => '环境法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3694',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3695 => 
    array (
      'linkageid' => '3695',
      'name' => '医疗保健法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3695',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3696 => 
    array (
      'linkageid' => '3696',
      'name' => '知识产权法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3696',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3697 => 
    array (
      'linkageid' => '3697',
      'name' => '海事法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3697',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3698 => 
    array (
      'linkageid' => '3698',
      'name' => '劳动法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3698',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3699 => 
    array (
      'linkageid' => '3699',
      'name' => '经济法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3699',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3700 => 
    array (
      'linkageid' => '3700',
      'name' => '公司法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3700',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3701 => 
    array (
      'linkageid' => '3701',
      'name' => '税法',
      'style' => '',
      'parentid' => '3559',
      'child' => '0',
      'arrchildid' => '3701',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3702 => 
    array (
      'linkageid' => '3702',
      'name' => '生物技术',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3702',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3703 => 
    array (
      'linkageid' => '3703',
      'name' => '神经生物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3703',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3704 => 
    array (
      'linkageid' => '3704',
      'name' => '生态学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3704',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3705 => 
    array (
      'linkageid' => '3705',
      'name' => '细胞生物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3705',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3706 => 
    array (
      'linkageid' => '3706',
      'name' => '微生物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3706',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3707 => 
    array (
      'linkageid' => '3707',
      'name' => '分子生物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3707',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3708 => 
    array (
      'linkageid' => '3708',
      'name' => '动物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3708',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3709 => 
    array (
      'linkageid' => '3709',
      'name' => '生物信息学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3709',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3710 => 
    array (
      'linkageid' => '3710',
      'name' => '植物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3710',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3711 => 
    array (
      'linkageid' => '3711',
      'name' => '发育生物学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3711',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3712 => 
    array (
      'linkageid' => '3712',
      'name' => '解剖学',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3712',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3713 => 
    array (
      'linkageid' => '3713',
      'name' => '生物物理',
      'style' => '',
      'parentid' => '3564',
      'child' => '0',
      'arrchildid' => '3713',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3727 => 
    array (
      'linkageid' => '3727',
      'name' => '咨询心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3727',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3728 => 
    array (
      'linkageid' => '3728',
      'name' => '法医心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3728',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3729 => 
    array (
      'linkageid' => '3729',
      'name' => '临床心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3729',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3730 => 
    array (
      'linkageid' => '3730',
      'name' => '职业心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3730',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3731 => 
    array (
      'linkageid' => '3731',
      'name' => '组织心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3731',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3732 => 
    array (
      'linkageid' => '3732',
      'name' => '神经心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3732',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3733 => 
    array (
      'linkageid' => '3733',
      'name' => '社会心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3733',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3734 => 
    array (
      'linkageid' => '3734',
      'name' => '儿童心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3734',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3735 => 
    array (
      'linkageid' => '3735',
      'name' => '发展心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3735',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3736 => 
    array (
      'linkageid' => '3736',
      'name' => '应用心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3736',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3737 => 
    array (
      'linkageid' => '3737',
      'name' => '认知心理学',
      'style' => '',
      'parentid' => '3565',
      'child' => '0',
      'arrchildid' => '3737',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3738 => 
    array (
      'linkageid' => '3738',
      'name' => '环境管理',
      'style' => '',
      'parentid' => '3567',
      'child' => '0',
      'arrchildid' => '3738',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3739 => 
    array (
      'linkageid' => '3739',
      'name' => '可持续管理',
      'style' => '',
      'parentid' => '3567',
      'child' => '0',
      'arrchildid' => '3739',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3740 => 
    array (
      'linkageid' => '3740',
      'name' => '环境科学',
      'style' => '',
      'parentid' => '3567',
      'child' => '0',
      'arrchildid' => '3740',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3741 => 
    array (
      'linkageid' => '3741',
      'name' => '水资源管理',
      'style' => '',
      'parentid' => '3567',
      'child' => '0',
      'arrchildid' => '3741',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3742 => 
    array (
      'linkageid' => '3742',
      'name' => '环境政策',
      'style' => '',
      'parentid' => '3567',
      'child' => '0',
      'arrchildid' => '3742',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3743 => 
    array (
      'linkageid' => '3743',
      'name' => '环境设计',
      'style' => '',
      'parentid' => '3567',
      'child' => '0',
      'arrchildid' => '3743',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3744 => 
    array (
      'linkageid' => '3744',
      'name' => '新闻',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3744',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3745 => 
    array (
      'linkageid' => '3745',
      'name' => '公共关系',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3745',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3746 => 
    array (
      'linkageid' => '3746',
      'name' => '数字媒体',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3746',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3747 => 
    array (
      'linkageid' => '3747',
      'name' => '大众传播',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3747',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3748 => 
    array (
      'linkageid' => '3748',
      'name' => '广告',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3748',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3749 => 
    array (
      'linkageid' => '3749',
      'name' => '媒体管理',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3749',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3750 => 
    array (
      'linkageid' => '3750',
      'name' => '媒体研究',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3750',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3751 => 
    array (
      'linkageid' => '3751',
      'name' => '新媒体',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3751',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3752 => 
    array (
      'linkageid' => '3752',
      'name' => '传播管理',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3752',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3753 => 
    array (
      'linkageid' => '3753',
      'name' => '传播研究',
      'style' => '',
      'parentid' => '3562',
      'child' => '0',
      'arrchildid' => '3753',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3754 => 
    array (
      'linkageid' => '3754',
      'name' => '社会工作',
      'style' => '',
      'parentid' => '3563',
      'child' => '0',
      'arrchildid' => '3754',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3755 => 
    array (
      'linkageid' => '3755',
      'name' => '公共政策',
      'style' => '',
      'parentid' => '3563',
      'child' => '0',
      'arrchildid' => '3755',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3756 => 
    array (
      'linkageid' => '3756',
      'name' => '社会政策',
      'style' => '',
      'parentid' => '3563',
      'child' => '0',
      'arrchildid' => '3756',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3757 => 
    array (
      'linkageid' => '3757',
      'name' => '公共管理',
      'style' => '',
      'parentid' => '3563',
      'child' => '0',
      'arrchildid' => '3757',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3758 => 
    array (
      'linkageid' => '3758',
      'name' => '政治经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3758',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3759 => 
    array (
      'linkageid' => '3759',
      'name' => '发展经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3759',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3760 => 
    array (
      'linkageid' => '3760',
      'name' => '计量经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3760',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3761 => 
    array (
      'linkageid' => '3761',
      'name' => '卫生经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3761',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3762 => 
    array (
      'linkageid' => '3762',
      'name' => '国际经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3762',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3763 => 
    array (
      'linkageid' => '3763',
      'name' => '应用经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3763',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3764 => 
    array (
      'linkageid' => '3764',
      'name' => '土地经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3764',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3765 => 
    array (
      'linkageid' => '3765',
      'name' => '环境经济学',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3765',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3766 => 
    array (
      'linkageid' => '3766',
      'name' => '经济政策',
      'style' => '',
      'parentid' => '3568',
      'child' => '0',
      'arrchildid' => '3766',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3767 => 
    array (
      'linkageid' => '3767',
      'name' => '海洋科学',
      'style' => '',
      'parentid' => '3569',
      'child' => '0',
      'arrchildid' => '3767',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3768 => 
    array (
      'linkageid' => '3768',
      'name' => '地理',
      'style' => '',
      'parentid' => '3569',
      'child' => '0',
      'arrchildid' => '3768',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3769 => 
    array (
      'linkageid' => '3769',
      'name' => '大气科学',
      'style' => '',
      'parentid' => '3569',
      'child' => '0',
      'arrchildid' => '3769',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3770 => 
    array (
      'linkageid' => '3770',
      'name' => '地理信息系统',
      'style' => '',
      'parentid' => '3569',
      'child' => '0',
      'arrchildid' => '3770',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3771 => 
    array (
      'linkageid' => '3771',
      'name' => '地质学',
      'style' => '',
      'parentid' => '3569',
      'child' => '0',
      'arrchildid' => '3771',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3772 => 
    array (
      'linkageid' => '3772',
      'name' => '遥感科学',
      'style' => '',
      'parentid' => '3569',
      'child' => '0',
      'arrchildid' => '3772',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3778 => 
    array (
      'linkageid' => '3778',
      'name' => '数学',
      'style' => '',
      'parentid' => '3570',
      'child' => '0',
      'arrchildid' => '3778',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3779 => 
    array (
      'linkageid' => '3779',
      'name' => '统计学',
      'style' => '',
      'parentid' => '3570',
      'child' => '0',
      'arrchildid' => '3779',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3780 => 
    array (
      'linkageid' => '3780',
      'name' => '精算',
      'style' => '',
      'parentid' => '3570',
      'child' => '0',
      'arrchildid' => '3780',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3781 => 
    array (
      'linkageid' => '3781',
      'name' => '环境卫生',
      'style' => '',
      'parentid' => '3572',
      'child' => '0',
      'arrchildid' => '3781',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3782 => 
    array (
      'linkageid' => '3782',
      'name' => '公共卫生管理',
      'style' => '',
      'parentid' => '3572',
      'child' => '0',
      'arrchildid' => '3782',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3783 => 
    array (
      'linkageid' => '3783',
      'name' => '生物统计',
      'style' => '',
      'parentid' => '3572',
      'child' => '0',
      'arrchildid' => '3783',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3784 => 
    array (
      'linkageid' => '3784',
      'name' => '流行病学',
      'style' => '',
      'parentid' => '3572',
      'child' => '0',
      'arrchildid' => '3784',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3785 => 
    array (
      'linkageid' => '3785',
      'name' => '天体物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3785',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3786 => 
    array (
      'linkageid' => '3786',
      'name' => '量子物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3786',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3787 => 
    array (
      'linkageid' => '3787',
      'name' => '核物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3787',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3788 => 
    array (
      'linkageid' => '3788',
      'name' => '光学物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3788',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3789 => 
    array (
      'linkageid' => '3789',
      'name' => '原子物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3789',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3790 => 
    array (
      'linkageid' => '3790',
      'name' => '生物物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3790',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3791 => 
    array (
      'linkageid' => '3791',
      'name' => '粒子物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3791',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3792 => 
    array (
      'linkageid' => '3792',
      'name' => '应用物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3792',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3793 => 
    array (
      'linkageid' => '3793',
      'name' => '凝聚态物理',
      'style' => '',
      'parentid' => '3573',
      'child' => '0',
      'arrchildid' => '3793',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3794 => 
    array (
      'linkageid' => '3794',
      'name' => '营养学',
      'style' => '',
      'parentid' => '3575',
      'child' => '0',
      'arrchildid' => '3794',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3795 => 
    array (
      'linkageid' => '3795',
      'name' => '食品',
      'style' => '',
      'parentid' => '3575',
      'child' => '0',
      'arrchildid' => '3795',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3796 => 
    array (
      'linkageid' => '3796',
      'name' => '生物化学',
      'style' => '',
      'parentid' => '3574',
      'child' => '0',
      'arrchildid' => '3796',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3797 => 
    array (
      'linkageid' => '3797',
      'name' => '分析化学',
      'style' => '',
      'parentid' => '3574',
      'child' => '0',
      'arrchildid' => '3797',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3798 => 
    array (
      'linkageid' => '3798',
      'name' => '有机化学',
      'style' => '',
      'parentid' => '3574',
      'child' => '0',
      'arrchildid' => '3798',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3799 => 
    array (
      'linkageid' => '3799',
      'name' => '化学研究',
      'style' => '',
      'parentid' => '3574',
      'child' => '0',
      'arrchildid' => '3799',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3800 => 
    array (
      'linkageid' => '3800',
      'name' => '无机化学',
      'style' => '',
      'parentid' => '3574',
      'child' => '0',
      'arrchildid' => '3800',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3801 => 
    array (
      'linkageid' => '3801',
      'name' => '城市设计',
      'style' => '',
      'parentid' => '3576',
      'child' => '0',
      'arrchildid' => '3801',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3802 => 
    array (
      'linkageid' => '3802',
      'name' => '城市规划',
      'style' => '',
      'parentid' => '3576',
      'child' => '0',
      'arrchildid' => '3802',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3803 => 
    array (
      'linkageid' => '3803',
      'name' => '城市研究',
      'style' => '',
      'parentid' => '3576',
      'child' => '0',
      'arrchildid' => '3803',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3804 => 
    array (
      'linkageid' => '3804',
      'name' => '农业',
      'style' => '',
      'parentid' => '3577',
      'child' => '0',
      'arrchildid' => '3804',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3805 => 
    array (
      'linkageid' => '3805',
      'name' => '林业',
      'style' => '',
      'parentid' => '3577',
      'child' => '0',
      'arrchildid' => '3805',
      'keyid' => '3551',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
  ),
);
?>