<?php
return array (
  0 => 
  array (
    'id' => '22',
    'catid' => '37',
    'typeid' => '0',
    'title' => '去留学网 留学个人陈述',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0826/20150826030346478.jpg',
    'keywords' => '去留学网 留学个人陈述',
    'description' => '去留学网 文书创作 留学个人陈述',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=show&catid=12&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'quliuxue1357',
    'inputtime' => '1421050727',
    'updatetime' => '1440572690',
    'content' => '去留学网 留学背景提升',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  1 => 
  array (
    'id' => '16',
    'catid' => '37',
    'typeid' => '0',
    'title' => '去留学网 英国全套文书',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0826/20150826030509194.jpg',
    'keywords' => '去留学网 英国全套文书',
    'description' => '去留学网 文书创作 英国全套文书',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=show&catid=12&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1418785678',
    'updatetime' => '1440572761',
    'content' => '去留学网 留学DIY 留学中介<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  2 => 
  array (
    'id' => '15',
    'catid' => '37',
    'typeid' => '0',
    'title' => '去留学网 推荐信',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0826/20150826032442301.png',
    'keywords' => '去留学网 推荐信',
    'description' => '去留学网 推荐信',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=show&catid=12&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1418785662',
    'updatetime' => '1440573902',
    'content' => '去留学网 推荐信',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
);
?>