<?php
return array (
  0 => 
  array (
    'id' => '25',
    'catid' => '15',
    'typeid' => '0',
    'title' => '白璐 内蒙古工业大学',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0211/20150211110513803.png',
    'keywords' => '去留学网 留学案例',
    'description' => '去留学网',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=15&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421915956',
    'updatetime' => '1423624315',
    'content' => '1.昆士兰大学 Master of Business<br />
2.悉尼大学 Master of Commerce<br />
3.莫纳什大学 Master of Business',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'oldschool' => '',
    'oneju' => '2分钟前，来自武汉的李同学生成了选校报告！',
  ),
  1 => 
  array (
    'id' => '24',
    'catid' => '15',
    'typeid' => '0',
    'title' => '李妍严',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/thumb_407_407_20150110042521230.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '1 爱丁堡大学 心里学2 阿斯顿大学 组织行为学3 格拉斯哥大学 心里学',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=15&id=24',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1420871501',
    'updatetime' => '1421198041',
    'content' => '1.爱丁堡大学 心理学&nbsp;&nbsp;&nbsp;&nbsp;<br />
2.阿斯顿大学 组织行为学<br />
<p>
	3.格拉斯哥大学 心理学
</p>
<p>
	<br />
</p>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'oldschool' => '同济大学',
    'oneju' => '10秒前，来自上海的周同学申请了中介评估方案！',
  ),
  2 => 
  array (
    'id' => '23',
    'catid' => '15',
    'typeid' => '0',
    'title' => '姜嘉瑶',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/thumb_400_400_20150110042855657.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '1 帝国理工学院 Environmental Engineering2 布里斯托大学 Environmental Management3 爱丁堡大学 Environmental Management',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=15&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1420871113',
    'updatetime' => '1421026917',
    'content' => '1.帝国理工学院 Environmental Engineering<br />
2.布里斯托大学 Environmental Management<br />
3.爱丁堡大学 Environmental Management<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'oldschool' => '同济大学',
    'oneju' => '4小时前，来自广州的戴同学申请了留学保保计划！',
  ),
  3 => 
  array (
    'id' => '22',
    'catid' => '15',
    'typeid' => '0',
    'title' => '汪严希',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/thumb_200_200_20150110042943606.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '伦敦大学学院 Urban Design伯明翰大学 Urban Regeneration谢菲尔德大学 Urban Design',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=15&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1420870785',
    'updatetime' => '1421026966',
    'content' => '伦敦大学学院 Urban Design<br />
伯明翰大学&nbsp; Urban Regeneration<br />
谢菲尔德大学 Urban Design<br />
<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'oldschool' => '华南理工大学',
    'oneju' => '3小时前，来自成都的汪同学申请了免费预约留学中介！',
  ),
  4 => 
  array (
    'id' => '21',
    'catid' => '15',
    'typeid' => '0',
    'title' => '余晓',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/thumb_174_174_20150110043623918.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '1 圣安德鲁斯大学 Management2 杜伦大学 MSc Management',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=15&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1420870991',
    'updatetime' => '1421027013',
    'content' => '1.圣安德鲁斯大学 Management<br />
2.杜伦大学 MSc Management',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'oldschool' => '四川大学',
    'oneju' => '2小时前，来自美国的江同学申请了免费预约留学中介！',
  ),
  5 => 
  array (
    'id' => '20',
    'catid' => '15',
    'typeid' => '0',
    'title' => '严潇',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/thumb_407_407_20150110043654890.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '1 谢菲尔德大学 Marketing Management2 埃克塞特大学 Marketing3 约克大学 International Business',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=15&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1420870489',
    'updatetime' => '1421027687',
    'content' => '1.谢菲尔德大学 Marketing Management<br />
2.埃克塞特大学 Marketing<br />
3.约克大学 International Business <br />
<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
    'oldschool' => '上海财经大学',
    'oneju' => '3秒前，来自美国的白同学免费获取了选校报告！',
  ),
);
?>