<?php
return array (
  0 => 
  array (
    'id' => '20',
    'catid' => '16',
    'typeid' => '0',
    'title' => '去留学网 选校引擎',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0210/20150210041015639.jpg',
    'keywords' => '去留学网 留学中介排名',
    'description' => '去留学 选校引擎',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=lists&catid=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'quliuxue1357',
    'inputtime' => '1421041773',
    'updatetime' => '1423555820',
  ),
  1 => 
  array (
    'id' => '19',
    'catid' => '16',
    'typeid' => '0',
    'title' => '去留学网 留学DIY 在线课程',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/20150112014830510.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '去留学网针对留学申请准备期、申请执行期、申请后期三个阶段推出免费留学课程，免费课程将陆续在去留学网络平台上以视频和音频的形式发布。',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=16&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421041700',
    'updatetime' => '1422102922',
  ),
  2 => 
  array (
    'id' => '9',
    'catid' => '16',
    'typeid' => '0',
    'title' => '去留学网 申请材料索引贴',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/20150112013321802.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '去留学网 留学DIY 留学中介',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=16&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1418720677',
    'updatetime' => '1422263553',
  ),
  3 => 
  array (
    'id' => '2',
    'catid' => '16',
    'typeid' => '0',
    'title' => '去留学网留学中介评估',
    'style' => '',
    'thumb' => '/style/picture/banner-01.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=lists&catid=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1417493733',
    'updatetime' => '1422082872',
  ),
  4 => 
  array (
    'id' => '1',
    'catid' => '16',
    'typeid' => '0',
    'title' => '去留学网英澳免费留学申请',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0112/20150112123227507.jpg',
    'keywords' => '去留学网 留学DIY 留学中介',
    'description' => '提示：替换右边的banner大图，加好下面的链接就可以。',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=lists&catid=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1417493694',
    'updatetime' => '1422103362',
  ),
);
?>