<?php
return array (
  0 => 
  array (
    'id' => '21',
    'catid' => '36',
    'typeid' => '0',
    'title' => '去留学网 个人陈述翻译',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0826/20150826034018950.jpg',
    'keywords' => '去留学网 个人陈述翻译',
    'description' => '去留学网 个人陈述翻译',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=show&catid=12&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'quliuxue1357',
    'inputtime' => '1421050551',
    'updatetime' => '1440574857',
    'content' => '去留学网 个人陈述翻译',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  1 => 
  array (
    'id' => '14',
    'catid' => '36',
    'typeid' => '0',
    'title' => '学科论文翻译',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0826/20150826033056455.jpg',
    'keywords' => '学科论文翻译',
    'description' => '学科论文翻译',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=show&catid=12&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1418785639',
    'updatetime' => '1440574291',
    'content' => '去留学网 留学文书定制<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  2 => 
  array (
    'id' => '13',
    'catid' => '36',
    'typeid' => '0',
    'title' => '去留学网 推荐信翻译',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0826/20150826033605405.jpg',
    'keywords' => '去留学网 推荐信翻译',
    'description' => '去留学网 定制留学文书',
    'posids' => '0',
    'url' => 'http://www.quliuxue.net.cn/index.php?m=content&c=index&a=show&catid=12&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1418785629',
    'updatetime' => '1440574595',
    'content' => '去留学网 推荐信翻译',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
);
?>