<?php
return array (
  0 => 
  array (
    'id' => '10',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Keddy',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0415/20150415042723958.png',
    'keywords' => '',
    'description' => '去留学网文书顾问，波士顿学院教育学硕士，英文素养高，有长期的英语口笔译经验，熟悉欧美等国家地区的名校。性格开朗热情，善于与学生沟通',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1429086279',
    'updatetime' => '1429086703',
    'zhicheng' => '高级文书顾问',
    'content' => '<span style="font-family:新宋体, tahoma, arial, 宋体, sans-serif;font-size:14px;line-height:24px;white-space:normal;">去留学网文书顾问，波士顿学院教育学硕士，英文素养高，有长期的英语口笔译经验，熟悉欧美等国家地区的名校。性格开朗热情，善于与学生沟通，能够根据学生的特色，进行个性化的文书创作，并为学生提供包括选校、材料准备、申请、面试辅导和签证办理等环节的辅导服务。</span>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Cherry ',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0120/20150120041159582.jpg',
    'keywords' => '',
    'description' => '上海交大 武汉大学联合培养在读MBA,中国职业规划师CCDM,MBTI认证施测师，国家生涯规划师。Qu留学网高级合伙人，首席运营官。加入Qu网前，Ch',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admina',
    'inputtime' => '1421939700',
    'updatetime' => '1421808390',
    'zhicheng' => '金牌咨询顾问',
    'content' => '上海交大/武汉大学联合培养在读MBA,中国职业规划师CCDM,MBTI认证施测师，国家生涯规划师。Qu留学网高级合伙人，首席运营官。加入Qu网前，Cherry曾任职于某IT巨头市场研究与品牌管理部门，拥有丰富的商业实践经验，因此特别擅长于英美商科留学申请方案的规划和制定。<a href="http://www.quliuxue.net.cn" target="_blank">查看详细介绍</a><br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  2 => 
  array (
    'id' => '9',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Anna ',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0121/20150121104035729.png',
    'keywords' => '',
    'description' => '从事教育行业多年，在办理美国，英国，香港等留学业务上积累了丰富的经验。擅长通过挖掘学生背景，帮助学生理清思路，专注于商科、理工科研',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421808000',
    'updatetime' => '1421808439',
    'zhicheng' => '资深申请顾问',
    'content' => '<span style="font-family:微软雅黑;"><span style="font-size:10.5000pt;">从事教育行业多年，在办理美国，英国，香港等留学业务上积累了丰富的经验。擅长通过挖掘学生背景，帮助学生理清思路，专注于商科、理工科研究申请，为学生制定合理的留学方案。从学生角度出发，真诚、热情的服务于每一位，深受学生及家长的喜爱。</span></span>',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Saya',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0118/20150118052649948.jpg',
    'keywords' => '',
    'description' => '毕业于武汉大学，曾前往法国留学，拥有丰富的留学经历，长期专注于英语系国家商科、理工科、文科的硕士和本科申请。基于大量的海外高校研究',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admina',
    'inputtime' => '1421767260',
    'updatetime' => '1422003169',
    'zhicheng' => '资深咨询顾问',
    'content' => '毕业于武汉大学，曾前往法国留学，拥有丰富的留学经历，长期专注于英语系国家商科、理工科、文科的硕士和本科申请。基于大量的海外高校研究资料和广泛的海外人脉，对英国、美国、加拿大等国的硕士申请有着深刻的见解。擅长帮助申请者挖掘学习生涯的闪光点，充分利用提升空间，争取获得最好的录取。热爱与人沟通，善于学习运用新知识。与来自多个国家的外籍人士有过深入交流，对海外文化有着独特见解。待人热情大方，活泼开朗而不失理性，赢得了诸多学生的信任。<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  4 => 
  array (
    'id' => '2',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Nicole',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0118/20150118061127479.jpg',
    'keywords' => '',
    'description' => '基于学科储备和专业研究优势，对金融与其他商科方向的申请服务有其独特的见解。真诚，热情，耐心的服务于每位学生，能站在学生的角度，以一',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admina',
    'inputtime' => '1421766900',
    'updatetime' => '1422437460',
    'zhicheng' => '资深咨询顾问',
    'content' => '基于学科储备和专业研究优势，对金融与其他商科方向的申请服务有其独特的见解。真诚，热情，耐心的服务于每位学生，能站在学生的角度，以一颗真诚的心与学
生沟通。善于针对每个学生的特性与需求，引导他们发掘自身的独特,闪光之处，量体裁衣，全方位帮助学生深入剖析和安排留学各项事宜和留学计划，根据学生的
自身条件为学生提供最专业的留学规划、背景提升、职业规划、院校申请、奖学金申请等服务，为学生申请最好最适合他们的学校，制定最适合的个性化留学方案，
让每一个出国的莘莘学子能够迈入理想的学校，实现人生价值！<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  5 => 
  array (
    'id' => '8',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Catherine',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0120/20150120044215280.jpg',
    'keywords' => '',
    'description' => '国内知名211院校英语教育硕士，拥有上海市高级口译证书，多年留学行业工作经验，熟悉英美等国家的名校申请，性格热情，有亲和力，敏锐地发',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421743323',
    'updatetime' => '1421808589',
    'zhicheng' => '资深申请顾问',
    'content' => '国内知名211院校英语教育硕士，拥有上海市高级口译证书，多年留学行业工作经验，熟悉英美等国家的名校申请，性格热情，有亲和力，敏锐地发现学生自身的闪光点，为学生的留学进行科学规划和申请，制作有竞争力的文书材料；并为学生提供包括选校、材料准备、申请、面试和签证办理等环节的辅导服务，经手办理的学生遍布美国各大知名大学。',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  6 => 
  array (
    'id' => '7',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Summer',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0120/20150120043840526.jpg',
    'keywords' => '',
    'description' => '英语专业毕业,从事教师的经验培养了对每个学生认真负责的态度，也明白每个家长对自己孩子的拳拳之心。专注于英语系国家商科、理工科、文科',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421743063',
    'updatetime' => '1421808574',
    'zhicheng' => '资深申请顾问',
    'content' => '英语专业毕业,从事教师的经验培养了对每个学生认真负责的态度，也明白每个家长对自己孩子的拳拳之心。专注于英语系国家商科、理工科、文科的申请，为符合申请条件的学生制定合理的留学方案。多年英语专业学习，与不同国家外籍人士有过深入交流，对海外文化有着独特见解。留学，是人生的另一条起跑线上，很多家长和学生感到迷茫，“师者，传道，授业，解惑也”，热诚，真诚，耐心的服务于每位学生，站在学生角度帮助学生在留学的道路上扫清障碍，用专业、真心、同理心担负起学生和家长的信任，提供细心周到的咨询服务。',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  7 => 
  array (
    'id' => '6',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Julie',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0120/20150120042701492.jpg',
    'keywords' => '',
    'description' => '美国工学硕士、博士。美国化工协会会员，全奖赴美留学，后留美工作。在美期间，多次参加国际会议，亲历美国文化，游遍美国。本科毕业于西安',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421742413',
    'updatetime' => '1421743204',
    'zhicheng' => '高级文书顾问',
    'content' => '美国工学硕士、博士。美国化工协会会员，全奖赴美留学，后留美工作。在美期间，多次参加国际会议，亲历美国文化，游遍美国。本科毕业于西安交通大学，取得双学位(工程/英语)，在校期间以第一作者身份在英国著名环境类杂志发表论文一篇。Julie 老师负责去留学网客户美国工科文书的创作。',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  8 => 
  array (
    'id' => '5',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Evan',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0120/20150120042009212.jpg',
    'keywords' => '',
    'description' => 'Evan拥有中、美、英、法四国的学习经历。大学期间作为交换生去美国康奈尔大学学习，以专业第一的成绩毕业。其后，全奖赴法求学进行学术研究',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421742000',
    'updatetime' => '1429086427',
    'zhicheng' => '高级文书顾问',
    'content' => 'Evan拥有中、美、英、法四国的学习经历。大学期间作为交换生去美国康奈尔大学学习，以专业第一的成绩毕业。其后，全奖赴法求学进行学术研究。持有特许金融分析师(Chartered Financial Analyst)一级证书、国际固定收益与衍生品证书(IFID Certificate)，并且通过证券从业资格考试。<br />
EVAN负责Qu去留学网 金融和会计类文书的创作。<br />',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
  9 => 
  array (
    'id' => '4',
    'catid' => '50',
    'typeid' => '0',
    'title' => 'Alex',
    'style' => '',
    'thumb' => 'http://www.quliuxue.net.cn/uploadfile/2015/0120/thumb_66_76_20150119114837831.jpg',
    'keywords' => '',
    'description' => 'Alex老师是去留学网高级文书顾问，负责金融、会计、计算机等专业文书的创作和翻译，Alex物理计算机专业毕业，曾在英国伦敦著名的Gresham C',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=50&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'quliuxue1357',
    'inputtime' => '1421639307',
    'updatetime' => '1421740704',
    'zhicheng' => '外籍文书顾问',
    'content' => 'Alex老师是去留学网高级文书顾问，负责金融、会计、计算机等专业文书的创作和翻译，Alex物理计算机专业毕业，曾在英国伦敦著名的Gresham Computing公司担任理财顾问，因此特别擅长计算机以及金融会计类文书创作。Alex老师汉语水平考试（HSK）五级，可以非常熟练的与申请者进行文书访谈。',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '10000',
    'template' => '',
    'paytype' => '0',
    'allow_comment' => '1',
    'relation' => '',
  ),
);
?>