<?php
return array (
  'admin' => 
  array (
    'module' => 'admin',
    'name' => 'admin',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'admin_email\' => \'phpcms@phpcms.cn\',
  \'maxloginfailedtimes\' => \'8\',
  \'minrefreshtime\' => \'2\',
  \'mail_type\' => \'1\',
  \'mail_server\' => \'smtp.qq.com\',
  \'mail_port\' => \'25\',
  \'category_ajax\' => \'0\',
  \'mail_user\' => \'service@quliuxue.net.cn\',
  \'mail_auth\' => \'1\',
  \'mail_from\' => \'service@quliuxue.net.cn\',
  \'mail_password\' => \'thinkwithu2015\',
  \'errorlog_size\' => \'20\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-18',
    'updatedate' => '2010-10-18',
  ),
  'member' => 
  array (
    'module' => 'member',
    'name' => '会员',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'allowregister\' => \'1\',
  \'choosemodel\' => \'1\',
  \'enablemailcheck\' => \'0\',
  \'enablcodecheck\' => \'1\',
  \'mobile_checktype\' => \'2\',
  \'user_sendsms_title\' => \'\',
  \'registerverify\' => \'0\',
  \'showapppoint\' => \'0\',
  \'rmb_point_rate\' => \'10\',
  \'defualtpoint\' => \'0\',
  \'defualtamount\' => \'0\',
  \'showregprotocol\' => \'0\',
  \'regprotocol\' => \'		 欢迎您注册成为去留学网用户
请仔细阅读下面的协议，只有接受协议才能继续进行注册。 
1．服务条款的确认和接纳
　　去留学网用户服务的所有权和运作权归去留学网拥有。去留学网所提供的服务将按照有关章程、服务条款和操作规则严格执行。用户通过注册程序点击“我同意” 按钮，即表示用户与去留学网达成协议并接受所有的服务条款。\',
  \'registerverifymessage\' => \' 欢迎您注册成为Qu留学用户，您的账号需要邮箱认证，点击下面链接进行认证：{click}
或者将网址复制到浏览器：{url}\',
  \'forgetpassword\' => \'尊敬的会员：{username}，您好！ 
<br />
您要求了重设您在去留学网的帐户密码。<br />

您可以点击下面的链接登陆或者将下面的链接复制到浏览器地址栏:<br />

{url}
<br />
这是一个一次性登陆链接，只能使用一次。此链接一天后失效，如果未使用并不会有任何作用。

登录后，您将被转到 
http://www.quliuxue.net.cn
页面进行密码修改。

<br /><br />
                       ---  这封邮件来自去留学网http://www.quliuxue.net.cn  \',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'pay' => 
  array (
    'module' => 'pay',
    'name' => '支付',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'digg' => 
  array (
    'module' => 'digg',
    'name' => '顶一下',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'special' => 
  array (
    'module' => 'special',
    'name' => '专题',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'content' => 
  array (
    'module' => 'content',
    'name' => '内容模块',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'search' => 
  array (
    'module' => 'search',
    'name' => '全站搜索',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  \'fulltextenble\' => \'1\',
  \'relationenble\' => \'1\',
  \'suggestenable\' => \'1\',
  \'sphinxenable\' => \'0\',
  \'sphinxhost\' => \'10.228.134.102\',
  \'sphinxport\' => \'9312\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'scan' => 
  array (
    'module' => 'scan',
    'name' => '木马扫描',
    'url' => 'scan',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'attachment' => 
  array (
    'module' => 'attachment',
    'name' => '附件',
    'url' => 'attachment',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'block' => 
  array (
    'module' => 'block',
    'name' => '碎片',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'collection' => 
  array (
    'module' => 'collection',
    'name' => '采集模块',
    'url' => 'collection',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'dbsource' => 
  array (
    'module' => 'dbsource',
    'name' => '数据源',
    'url' => '',
    'iscore' => '1',
    'version' => '',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'template' => 
  array (
    'module' => 'template',
    'name' => '模板风格',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'release' => 
  array (
    'module' => 'release',
    'name' => '发布点',
    'url' => '',
    'iscore' => '1',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-01',
    'updatedate' => '2010-09-06',
  ),
  'video' => 
  array (
    'module' => 'video',
    'name' => '视频库',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2012-09-28',
    'updatedate' => '2012-09-28',
  ),
  'announce' => 
  array (
    'module' => 'announce',
    'name' => '公告',
    'url' => 'announce/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '公告',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-11-30',
    'updatedate' => '2014-11-30',
  ),
  'comment' => 
  array (
    'module' => 'comment',
    'name' => '评论',
    'url' => 'comment/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '评论',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-11-30',
    'updatedate' => '2014-11-30',
  ),
  'link' => 
  array (
    'module' => 'link',
    'name' => '友情链接',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'is_post\' => \'1\',
    \'enablecheckcode\' => \'0\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'vote' => 
  array (
    'module' => 'vote',
    'name' => '投票',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => 'array (
  1 => 
  array (
    \'default_style\' => \'default\',
    \'vote_tp_template\' => \'vote_tp\',
    \'allowguest\' => \'1\',
    \'enabled\' => \'1\',
    \'interval\' => \'1\',
    \'credit\' => \'1\',
  ),
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'message' => 
  array (
    'module' => 'message',
    'name' => '短消息',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-09-06',
    'updatedate' => '2010-09-06',
  ),
  'mood' => 
  array (
    'module' => 'mood',
    'name' => '新闻心情',
    'url' => 'mood/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '新闻心情',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-11-30',
    'updatedate' => '2014-11-30',
  ),
  'poster' => 
  array (
    'module' => 'poster',
    'name' => '广告模块',
    'url' => 'poster/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '广告模块',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-11-30',
    'updatedate' => '2014-11-30',
  ),
  'formguide' => 
  array (
    'module' => 'formguide',
    'name' => '表单向导',
    'url' => 'formguide/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => 'formguide',
    'setting' => 'array (
  \'allowmultisubmit\' => \'1\',
  \'interval\' => \'30\',
  \'allowunreg\' => \'0\',
  \'mailmessage\' => \'用户向我们提交了表单数据，赶快去看看吧。\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2010-10-20',
    'updatedate' => '2010-10-20',
  ),
  'wap' => 
  array (
    'module' => 'wap',
    'name' => '手机门户',
    'url' => 'wap/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '手机门户',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-11-30',
    'updatedate' => '2014-11-30',
  ),
  'upgrade' => 
  array (
    'module' => 'upgrade',
    'name' => '在线升级',
    'url' => '',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-05-18',
    'updatedate' => '2011-05-18',
  ),
  'tag' => 
  array (
    'module' => 'tag',
    'name' => '标签向导',
    'url' => 'tag/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '标签向导',
    'setting' => '',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2014-11-30',
    'updatedate' => '2014-11-30',
  ),
  'sms' => 
  array (
    'module' => 'sms',
    'name' => '短信平台',
    'url' => 'sms/',
    'iscore' => '0',
    'version' => '1.0',
    'description' => '短信平台',
    'setting' => 'array (
  \'sms_enable\' => \'1\',
  \'userid\' => \'300366\',
  \'productid\' => \'5138\',
  \'sms_key\' => \'pgiE2JNlA5odt1zZkjJ2tbeiovPViTyN\',
)',
    'listorder' => '0',
    'disabled' => '0',
    'installdate' => '2011-09-02',
    'updatedate' => '2011-09-02',
  ),
);
?>